sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install python-pip make
  - python --version
  - sudo pip install --upgrade pip
  - sudo pip install git+https://github.com/ministryofjustice/semvertag.git

script:
 - make build